#!/bin/bash

#training script

set -e

cd DARK

if [ "$1" == "" ]
then 
	echo "WRITE THE DAMN FILEPATH TO SOME STARTING WEIGHT"
	exit 1
fi

./darknet detector train cfg/cat-dog-obj.data cfg/cat-dog-yolov3-tiny.cfg "../$1"




