#!/bin/bash

# Script to either live recog or video recog etc... 
#TODO modify the python file to complement this script

if [ "$1" == "" ]
then 
	python3 cascadaYolo_v5.py;
else 
	if [ "$2" == "" ]
	then 
		python3 cascadaYolo_v5.py "$1";
	else
		if [ "$3" == "" ]
		then 
			python3 cascadaYolo_v5.py $1 "$2";
		else 
			python3 cascadaYolo_v5.py $1 "$2" "$3";
		fi
	fi
fi
