#!/bin/bash

# script for simple detection usage, just write in this order imagepath, weight, and if you want to decrease the threshold for detection then do -thresh X. with X a float percentage

set -e 

cd DARK;

if [ "$1" == "" ]
then echo "Not the correct usage check -h";
fi

if [ "$1" == "-h" ]
then echo "usage: imagepath weightpath (option: -thresh x)";

else
	if [ "$3" == "" ]
	then 
		./darknet "detector" "test" "cfg/cat-dog-obj.data" "cfg/cat-dog-yolov3-tiny.cfg" "../$2" "../$1" 
	else
		echo "$4"
		echo "$3"
		./darknet "detector" "test" "cfg/cat-dog-obj.data" "cfg/cat-dog-yolov3-tiny.cfg" "../$2" "../$1" "$3" "$4"
	fi
fi

mv predictions.jpg ../result
cd python
python3 mic.py
